env:
    browser: true
    es2021: true
    jest: true
extends:
    - plugin:react/recommended
    - airbnb
overrides: []
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - react
    - jest
rules: { 'indent': ['error', 4, { 'SwitchCase': 1 }], 'comma-dangle': 'off', 'new-cap': 'off' }
